[package]
name = "rubeeru"
version = "0.1.0"
authors = ["caires"]

[dependencies]
rocket = "0.3.3"
rocket_codegen = "0.3.3"
rocket_contrib = "0.3.3"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
geojson = "0.9.0"
geo = "0.6.3"